### ISSUE TITLE
not all arguments converted during string formatting

### ISSUE THREAD

**Issue by vinthewrench** [gglockner/indigo-opensprinkler#1]
Hi  I am running the plugin  with the following setup.

Indigo 7.4.1
Python 2.7.10 (default, Feb 22 2019, 21:55:15) 
MAcOS 10,14.6

OpenSprinkler
App Version: 2.1.10 
Firmware: 2.1.9 (2) 
Hardware Version: 3.2 - DC

When I attempt to turn on a zone I get the following failure in the  Indigo Log

May 10, 2020 at 10:16:48 AM
   OpenSprinkler                   sent "OpenSprinkler" all zones off
   OpenSprinkler Error             Error in plugin execution ExecuteAction:

Traceback (most recent call last):
  File "plugin.py", line 146, in actionControlSprinkler
TypeError: not all arguments converted during string formatting

Status request works and stop all works,
but when I try and turn a zone on I get the failure .

any suggestions?

**Comment by gglockner** [comment]
My guess is there's an issue with zone names. Can you check your Indigo log for an error that looks like this:

send "[device] -[zone]" on failed

The value of [device] and [zone] will depend on your configuration.

**Comment by vinthewrench** [comment]
I never see the "send" command in the log 
my zone names are default. (S01)  etc
even changing the zone to Zone1 fails the same way.

**Comment by gglockner** [comment]
I think I see the issue - please download the latest version from master and let me know if that fixes it.

**Comment by vinthewrench** [comment]
now I get in the log 


" OpenSprinkler Error             send "Garden" zone "S01" on failed: 'rs'"

**Comment by gglockner** [comment]
Thanks, I think I found the issue. Please download the latest version from master and try it one more time.

**Comment by vinthewrench** [comment]
I am still getting 
 OpenSprinkler Error             send "Garden" zone "S08" on failed: 'rs'

walk me through some debugging and I will be happy to find the issue

**Comment by gglockner** [comment]
Please double-check that you upgraded to version 20200512. That fixes an issue where it was searching for a rain sensor ('rs') that is not connected to your OpenSprinkler.

**Comment by vinthewrench** [comment]
is it possible that the parameter is no longer called 'rs'. 

when I did a get options REST command to the device (/jo). I got back 


{"fwv":219,"tz":20,"ntp":1,"dhcp":1,"ip1":10,"ip2":10,"ip3":0,"ip4":181,"gw1":10,"gw2":10,"gw3":0,"gw4":1,"hp0":80,"hp1":0,"hwv":32,"ext":0,"sdt":0,"mas":0,"mton":0,"mtof":0,"wl":100,"den":1,"ipas":0,"devid":0,"bst":320,"uwt":0,"ntp1":50,"ntp2":97,"ntp3":210,"ntp4":169,"lg":1,"mas2":0,"mton2":0,"mtof2":0,"fwm":2,"fpr0":100,"fpr1":0,"re":0,"dns1":10,"dns2":10,"dns3":0,"dns4":1,"sar":0,"ife":0,"sn1t":1,"sn1o":0,"sn2t":0,"sn2o":1,"sn1on":0,"sn1of":0,"sn2on":0,"sn2of":0,"subn1":255,"subn2":255,"subn3":255,"subn4":0,"wimod":42,"reset":0,"dexp":0,"mexp":8,"hwt":220}

**Comment by vinthewrench** [comment]
{"fwv":219,"tz":20,"ntp":1,"dhcp":1,"ip1":10,"ip2":10,"ip3":0,"ip4":181,"gw1":10,"gw2":10,"gw3":0,"gw4":1,"hp0":80,"hp1":0,"hwv":32,"ext":0,"sdt":0,"mas":0,"mton":0,"mtof":0,"wl":100,"den":1,"ipas":0,"devid":0,"bst":320,"uwt":0,"ntp1":50,"ntp2":97,"ntp3":210,"ntp4":169,"lg":1,"mas2":0,"mton2":0,"mtof2":0,"fwm":2,"fpr0":100,"fpr1":0,"re":0,"dns1":10,"dns2":10,"dns3":0,"dns4":1,"sar":0,"ife":0,"sn1t":1,"sn1o":0,"sn2t":0,"sn2o":1,"sn1on":0,"sn1of":0,"sn2on":0,"sn2of":0,"subn1":255,"subn2":255,"subn3":255,"subn4":0,"wimod":42,"reset":0,"dexp":0,"mexp":8,"hwt":220}

**Comment by gglockner** [comment]
The exception handling at line 110 should handle the missing dictionary key, but build 20200512 used the wrong exception class. Build 20200512-172246 fixes that.

**Comment by vinthewrench** [comment]
looks like that fixed it --  thank you
